#pragma config(Motor,  motorD,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Gyro modes
0 - modeEV3Gyro_Angle
1 - modeEV3Gyro_Rate
2 - modeEV3Gyro_Fast
3 - modeEV3Gyro_RateAndAngle
4 - modeEV3Gyro_Calibration - Not utilized
*/
task main()
{
	// Set motor speeds to 20 and -20 to do a clockwise pivot turn
	motor[motorLeft] = 20;
	motor[motorRight] = 20;

	sleep(1000);

	// Stop the robot and wait 1 second
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	sleep(1000);
}
