#pragma config(Sensor, S4,     	Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorC,	motorLeft,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,  motorRight,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//----------------------------------------------------------------------------
//
//  $Workfile: KeepGyroAtZero.c$
//
//  $Revision: X$
//
//  Project:    PNW Code Wright
//
//                            Copyright (c) 2018
//                                Jim Wright
//                            All Rights Reserved
//
//  Modification History:
//  $Log:
//  $
//
//----------------------------------------------------------------------------

// --------------------------------------------------------------------
// Local function prototypes
// --------------------------------------------------------------------
int DeadBand(int axisVal);

// --------------------------------------------------------------------
// Purpose:
//     Keep the robot pointed at 'north'
//
// Notes:
// None.
// --------------------------------------------------------------------
task main()
{
	resetGyro(Gyro);

	while (true)
	{
		int angle = DeadBand(SensorValue[Gyro]);

		if(0 == angle)
		{
			motor[motorLeft] = 0;
			motor[motorRight] = 0;
		}
		else
		{
			if(angle > 0)
			{
				motor[motorLeft] = 20;
				motor[motorRight] = -20;
			}
			else
			{
				motor[motorLeft] = -20;
				motor[motorRight] = 20;
			}
		}
	}
}

// --------------------------------------------------------------------
// Purpose:
//     Zero out the noise when we are going slow
//
// Notes:
// None.
// --------------------------------------------------------------------
int DeadBand(int axisVal)
{
  if (axisVal < -4) {
    return axisVal;
  }

  if (axisVal > 4) {
    return axisVal;
  }

  return 0;
}
