#pragma config(Motor,  motorD,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//----------------------------------------------------------------------------
//
//  $Workfile: ForwardOneSecond.c$
//
//  $Revision: X$
//
//  Project:    PNW Code Wright
//
//                            Copyright (c) 2018
//                                Jim Wright
//                            All Rights Reserved
//
//  Modification History:
//  $Log:
//  $
//
//----------------------------------------------------------------------------

// --------------------------------------------------------------------
// Purpose:
//     Run the robot and stop after a second
//
// Notes:
// None.
// --------------------------------------------------------------------
task main()
{
	// Set motor speeds to 20
	motor[motorLeft] = 20;
	motor[motorRight] = 20;

	sleep(1000);

	// Stop the robot
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
}
